defmodule Mix.Tasks.Exscm.Version do
  use Mix.Task

  @shortdoc "Print current package version"

  @moduledoc """
  Print the current package version generated by Exscm.
  """
  def run(_) do
    IO.puts Exscm.get_version()
  end
end
